//
// Created by Eric Pfister on 11/17/20.
//

#ifndef FINAL_PROJECT_PFISTERFACTOR_INCLUDE_TOOLBAR_H_
#define FINAL_PROJECT_PFISTERFACTOR_INCLUDE_TOOLBAR_H_

class Toolbar {
 private:

};
#endif //FINAL_PROJECT_PFISTERFACTOR_INCLUDE_TOOLBAR_H_
